### ISSUE TITLE
Create Teams MongoDB Table and build integration to populate with API data

### ISSUE THREAD

**Issue by rking8888** [rking8888/kotkl-next#22]
Need to create new teams table. We can pre-populate manually with API data, but will need to integrate it into a page where we can either click a button or have it automatically update.

This older data in this table shouldn't change, and is pretty small already (12 teams) so we could potentially just rewrite this table every time. May need to think about it one last time to make sure we're not missing anything by rewriting it.

**Comment by jablan08** [comment]
pushed my branch code that has working code that can access mongodb collections, go ahead and grab that code and test it out!

**Comment by jablan08** [comment]
populated manager on team component, but definitely needs some styling
